// src/pages/insta/crypto-buys.tsx
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import type { ReactElement } from 'react'

type Coin = {
  symbol: string
  name: string
  score: number
  signal: string
}

type HomeSnapshot = {
  coinTopBuy?: Coin[]
}

type Props = {
  coins: Coin[]
  asOf: string
}

const CryptoBuysInsta: NextPage<Props> = ({ coins, asOf }) => {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-50 flex items-center justify-center">
      <Head>
        <title>Top 5 Crypto BUY Signals – Signalhub</title>
        <meta name="robots" content="noindex" />
        {/* Verberg cookie banners alleen op deze pagina */}
        <style>{`
          div[id*="cookie"],
          div[id*="Cookie"],
          div[class*="cookie"],
          div[class*="Cookie"] {
            display: none !important;
          }
        `}</style>
      </Head>

      <div className="w-[1080px] max-w-full px-8 py-10">
        <header className="mb-8">
          <h1 className="text-4xl font-bold tracking-tight">
            Top 5 Crypto BUY Signals
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Generated by Signalhub • {asOf}
          </p>
        </header>

        {coins.length === 0 ? (
          <p className="text-slate-400">
            No clear BUY signals at the moment.
          </p>
        ) : (
          <ol className="space-y-4">
            {coins.map((c, idx) => (
              <li
                key={c.symbol}
                className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-900/60 px-5 py-4"
              >
                <div>
                  <p className="text-sm text-slate-500">#{idx + 1}</p>
                  <p className="text-lg font-semibold">
                    {c.name}{' '}
                    <span className="text-slate-400 text-sm">
                      ({c.symbol})
                    </span>
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-sm uppercase tracking-wide text-emerald-400">
                    {c.signal}
                  </p>
                  <p className="text-sm text-slate-300">
                    Score: <span className="font-semibold">{c.score}</span>
                  </p>
                </div>
              </li>
            ))}
          </ol>
        )}

        <footer className="mt-10 text-xs text-slate-500">
          signalhub.tech • technical analysis signals • not financial advice
        </footer>
      </div>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps<Props> = async (ctx) => {
  const host = ctx.req.headers.host
  const isVercel = !!process.env.VERCEL_URL
  const protocol = isVercel ? 'https' : 'http'
  const baseUrl =
    process.env.NEXT_PUBLIC_BASE_URL || `${protocol}://${host}`

  let coins: Coin[] = []

  try {
    const res = await fetch(`${baseUrl}/api/home/snapshot`, {
      cache: 'no-store',
    })
    if (res.ok) {
      const snapshot: HomeSnapshot = await res.json()
      coins = (snapshot.coinTopBuy || []).slice(0, 5)
    }
  } catch (e) {
    coins = []
  }

  const now = new Date()
  const asOf = now.toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  })

  return {
    props: {
      coins,
      asOf,
    },
  }
}

// 🔽 Dit zorgt ervoor dat deze pagina GEEN globale layout gebruikt
;(CryptoBuysInsta as any).getLayout = function getLayout(page: ReactElement) {
  return page
}

export default CryptoBuysInsta