// src/lib/aex.ts
export type Ticker = { symbol:string; name:string };
export const AEX: Ticker[] = [
  { symbol: "ABN.AS", name: "ABN AMRO Bank" },
  { symbol: "ADYEN.AS", name: "Adyen" },
  { symbol: "AGN.AS", name: "Aegon" },
  { symbol: "AD.AS", name: "Ahold Delhaize" },
  { symbol: "AKZA.AS", name: "Akzo Nobel" },
  { symbol: "MT.AS", name: "ArcelorMittal" },
  { symbol: "ASM.AS", name: "ASM International" },
  { symbol: "ASML.AS", name: "ASML Holding" },
  { symbol: "ASRNL.AS", name: "ASR Nederland" },
  { symbol: "BESI.AS", name: "BE Semiconductor" },
  { symbol: "CVC.AS", name: "CVC Capital Partners" },
  { symbol: "DSFIR.AS", name: "DSM-Firmenich AG" },
  { symbol: "EXO.AS", name: "Exor NV" },
  { symbol: "HEIA.AS", name: "Heineken" },
  { symbol: "IMCD.AS", name: "IMCD" },
  { symbol: "INGA.AS", name: "ING Groep" },
  { symbol: "INPST.AS", name: "InPost" },
  { symbol: "JDEP.AS", name: "JDE Peet's" },
  { symbol: "TKWY.AS", name: "Just Eat Takeaway" },
  { symbol: "KPN.AS", name: "KPN" },
  { symbol: "NN.AS", name: "NN Group" },
  { symbol: "PHIA.AS", name: "Philips" },
  { symbol: "PRX.AS", name: "Prosus" },
  { symbol: "RAND.AS", name: "Randstad" },
  { symbol: "REN.AS", name: "RELX" },
  { symbol: "SHELL.AS", name: "Shell" },
  { symbol: "UMG.AS", name: "Universal Music Group" },
  { symbol: "UNA.AS", name: "Unilever" },
  { symbol: "WDP.BR", name: "WDP" },
  { symbol: "WKL.AS", name: "Wolters Kluwer" }
];