// src/lib/sp500.ts
export type SpRow = { symbol: string; name: string }

// Let op: symbolen zijn US tickers zonder suffix (AAPL, MSFT, ...).
// Je kunt deze lijst veilig uitbreiden – volg exact dezelfde structuur.
export const SP500: SpRow[] = [
  { symbol: 'AAPL', name: 'Apple' },
  { symbol: 'MSFT', name: 'Microsoft' },
  { symbol: 'GOOGL', name: 'Alphabet Class A' },
  { symbol: 'GOOG', name: 'Alphabet Class C' },
  { symbol: 'AMZN', name: 'Amazon' },
  { symbol: 'META', name: 'Meta Platforms' },
  { symbol: 'NVDA', name: 'NVIDIA' },
  { symbol: 'TSLA', name: 'Tesla' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway B' },
  { symbol: 'UNH', name: 'UnitedHealth' },
  { symbol: 'XOM', name: 'Exxon Mobil' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'JPM', name: 'JPMorgan Chase' },
  { symbol: 'V', name: 'Visa' },
  { symbol: 'PG', name: 'Procter & Gamble' },
  { symbol: 'MA', name: 'Mastercard' },
  { symbol: 'HD', name: 'Home Depot' },
  { symbol: 'AVGO', name: 'Broadcom' },
  { symbol: 'CVX', name: 'Chevron' },
  { symbol: 'MRK', name: 'Merck' },
  { symbol: 'PEP', name: 'PepsiCo' },
  { symbol: 'KO', name: 'Coca-Cola' },
  { symbol: 'ABBV', name: 'AbbVie' },
  { symbol: 'COST', name: 'Costco' },
  { symbol: 'ADBE', name: 'Adobe' },
  { symbol: 'NFLX', name: 'Netflix' },
  { symbol: 'WMT', name: 'Walmart' },
  { symbol: 'BAC', name: 'Bank of America' },
  { symbol: 'DIS', name: 'Walt Disney' },
  { symbol: 'PFE', name: 'Pfizer' },
  { symbol: 'CSCO', name: 'Cisco' },
  { symbol: 'ORCL', name: 'Oracle' },
  { symbol: 'INTC', name: 'Intel' },
  { symbol: 'AMD', name: 'Advanced Micro Devices' },
  { symbol: 'NKE', name: 'Nike' },
  { symbol: 'T', name: 'AT&T' },
  { symbol: 'VZ', name: 'Verizon' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'MCD', name: 'McDonald’s' },
  { symbol: 'TXN', name: 'Texas Instruments' },
];